Trying build-opts
Additional logging

Better docs

Use network not package

Use wasm-core-version

Quote missing

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -126,6 +126,7 @@ jobs:
             built-wasm-file-name-prefix: frequency_runtime
             release-wasm-file-name-prefix: frequency-rococo_runtime
             features: frequency-rococo-testnet
+            wasm-core-version: frequency-rococo
           - network: mainnet
             build-profile: production
             package: frequency-runtime
@@ -133,6 +134,7 @@ jobs:
             built-wasm-file-name-prefix: frequency_runtime
             release-wasm-file-name-prefix: frequency_runtime
             features: frequency
+            wasm-core-version: frequency
     runs-on: [self-hosted, Linux, X64]
     steps:
       - name: Set Ubuntu Env Vars
@@ -191,8 +193,8 @@ jobs:
       - name: Build Deterministic WASM
         run: |
           set -ex
-          srtool build \
-            --default-features="'--features on-chain-release-build,no-metadata-docs,${{matrix.features}}'" \
+          RUST_LOG=debug srtool build \
+            --build-opts="'--features on-chain-release-build,no-metadata-docs,${{matrix.features}}'" \
             --profile=${{matrix.build-profile}} \
             --package=${{matrix.package}} \
             --root
@@ -207,7 +209,8 @@ jobs:
       - name: Test WASM file
         run: |
           subwasm info ${{env.WASM_DIR}}/${{env.RELEASE_WASM_FILENAME}}
-          subwasm info ${{env.WASM_DIR}}/${{env.RELEASE_WASM_FILENAME}} | grep "Core version:.*${{matrix.package}}-${{env.RUNTIME_SPEC_VERSION}}"
+          subwasm info ${{env.WASM_DIR}}/${{env.RELEASE_WASM_FILENAME}} | grep "Core version:.*${{matrix.wasm-core-version}}-${{env.RUNTIME_SPEC_VERSION}}" || \
+            (echo "ERROR: WASM Core version didn't match ${{matrix.wasm-core-version}}-${{env.RUNTIME_SPEC_VERSION}}" && exit 1)
       - name: Upload Artifact
         uses: actions/upload-artifact@v3
         with:
