add self-hosted runners (#727)
# Goal
The goal of this PR is to switch to self-hosted runners for compute
intensive jobs.

Closes #723

diff --git a/.github/workflows/verify-pr-commit.yml b/.github/workflows/verify-pr-commit.yml
--- a/.github/workflows/verify-pr-commit.yml
+++ b/.github/workflows/verify-pr-commit.yml
@@ -47,7 +47,7 @@ jobs:
     needs: changes
     if: needs.changes.outputs.build-binary == 'true'
     name: Compile Frequency Project
-    runs-on: ubuntu-20.04
+    runs-on: [self-hosted, Linux, X64]
     env:
       NETWORK: mainnet
     steps:
@@ -55,6 +55,7 @@ jobs:
         run: |
           echo "BIN_DIR=target/$BUILD_PROFILE" >> $GITHUB_ENV
           echo "BUILT_BIN_FILENAME=frequency" >> $GITHUB_ENV
+          echo "HOME=/home/ubuntu" >> $GITHUB_ENV
       - name: Check Out Repo
         uses: actions/checkout@v3
       # # XXX Keep this step as it lets us skip full binary builds during development/testing
@@ -64,11 +65,6 @@ jobs:
       #   with:
       #     path: ${{env.BIN_DIR}}/${{env.BUILT_BIN_FILENAME}}
       #     key: ${{runner.os}}-${{env.NETWORK}}-${{github.ref_name}}
-      - name: Save/Restore Dependencies from Cache
-        if: steps.cache-binary.outputs.cache-hit != 'true'
-        uses: Swatinem/rust-cache@v2
-        with:
-          shared-key: ${{env.RUST_TOOLCHAIN}}
       - name: Install Rust Toolchain
         if: steps.cache-binary.outputs.cache-hit != 'true'
         uses: actions-rs/toolchain@v1
@@ -77,6 +73,11 @@ jobs:
           profile: minimal
           target: wasm32-unknown-unknown
           toolchain: stable
+      - name: Cache Rust Dependencies
+        if: steps.cache-binary.outputs.cache-hit != 'true'
+        uses: Swatinem/rust-cache@v2
+        with:
+          shared-key: ${{env.RUST_TOOLCHAIN}}
       - name: Compile Binary
         if: steps.cache-binary.outputs.cache-hit != 'true'
         run: |
@@ -114,10 +115,10 @@ jobs:
       - name: Run Cargo Deny
         run: cargo deny check --hide-inclusion-graph -c .cargo-deny.toml
 
-  check-rust-code-format:
+  verify-rust-code-format:
     needs: changes
     if: needs.changes.outputs.rust == 'true'
-    name: Check Rust Code Format
+    name: Verify Rust Code Format
     runs-on: ubuntu-20.04
     steps:
       - name: Check Out Repo
@@ -136,8 +137,11 @@ jobs:
     needs: changes
     if: needs.changes.outputs.rust == 'true'
     name: Lint Rust Code
-    runs-on: ubuntu-20.04
+    runs-on: [self-hosted, Linux, X64]
     steps:
+      - name: Set Env Vars
+        run: |
+          echo "HOME=/home/ubuntu" >> $GITHUB_ENV
       - name: Check Out Repo
         uses: actions/checkout@v3
       - name: Install Rust Toolchain
@@ -154,31 +158,40 @@ jobs:
             -- \
             -D warnings
 
-  check-rust-docs:
+  verify-rust-developer-docs:
     needs: changes
     if: needs.changes.outputs.rust == 'true'
-    name: Check Rust Docs
-    runs-on: ubuntu-20.04
+    name: Verify Rust Developer Docs
+    runs-on: [self-hosted, Linux, X64]
     steps:
+      - name: Set Env Vars
+        run: |
+          echo "HOME=/home/ubuntu" >> $GITHUB_ENV
       - name: Check Out Repo
         uses: actions/checkout@v3
       - name: Install Rust Toolchain
         uses: actions-rs/toolchain@v1
         with:
+          toolchain: stable
           default: true
           profile: minimal
           target: wasm32-unknown-unknown
-          components: rust-docs
-          toolchain: stable
+      - name: Cache Rust Dependencies
+        uses: Swatinem/rust-cache@v2
+        with:
+          shared-key: ${{env.RUST_TOOLCHAIN}}
       - name: Build Rust Docs
         run: RUSTDOCFLAGS="--enable-index-page --check -Zunstable-options" cargo doc --no-deps --all-features
 
-  check-rust-packages-and-deps:
+  verify-rust-packages-and-deps:
     needs: changes
     if: needs.changes.outputs.rust == 'true'
-    name: Check Rust Packages and Dependencies
-    runs-on: ubuntu-20.04
+    name: Verify Rust Packages and Dependencies
+    runs-on: [self-hosted, Linux, X64]
     steps:
+      - name: Set Env Vars
+        run: |
+          echo "HOME=/home/ubuntu" >> $GITHUB_ENV
       - name: Check Out Repo
         uses: actions/checkout@v3
       - name: Install Rust Toolchain
@@ -194,8 +207,11 @@ jobs:
     needs: changes
     if: needs.changes.outputs.rust == 'true'
     name: Run Rust Tests
-    runs-on: ubuntu-20.04
+    runs-on: [self-hosted, Linux, X64]
     steps:
+      - name: Set Env Vars
+        run: |
+          echo "HOME=/home/ubuntu" >> $GITHUB_ENV
       - name: Check Out Repo
         uses: actions/checkout@v3
       - name: Install Rust Toolchain
@@ -242,6 +258,74 @@ jobs:
         with:
           fail_ci_if_error: false # optional (default = false)
           verbose: true # optional (default = false)
+
+  verify-build-runtimes:
+    needs: changes
+    if: needs.changes.outputs.rust == 'true'
+    name: Verify Build Runtime for ${{matrix.network}}
+    strategy:
+      matrix:
+        network: [rococo, mainnet]
+        include:
+          - network: rococo
+            build-profile: production
+            package: frequency-runtime
+            runtime-dir: runtime/frequency
+            features: frequency-rococo-testnet
+          - network: mainnet
+            build-profile: production
+            package: frequency-runtime
+            runtime-dir: runtime/frequency
+            features: frequency
+    runs-on: [self-hosted, Linux, X64]
+    steps:
+      - name: Set Ubuntu Env Vars
+        run: |
+          echo "HOME=/home/ubuntu" >> $GITHUB_ENV
+      - name: Check Out Repo
+        uses: actions/checkout@v3
+      - name: Install Rust Toolchain
+        uses: actions-rs/toolchain@v1
+        with:
+          default: true
+          profile: minimal
+          toolchain: stable
+      - name: Install Docker
+        run: |
+          curl -fsSL https://get.docker.com -o get-docker.sh
+          sudo sh get-docker.sh
+      - name: Extract Runtime Spec Version
+        run: |
+          echo "RUNTIME_SPEC_VERSION=$(sed -nr 's/spec_version:\s*([0-9]+),/\1/p' \
+            ${{matrix.runtime-dir}}/src/lib.rs | tr -d '[:space:]')" >> $GITHUB_ENV
+      - name: Validate Extracted Version
+        run: |
+          echo "Runtime Spec Version:|${{env.RUNTIME_SPEC_VERSION}}|"
+          echo "Runtime Spec Version:||$RUNTIME_SPEC_VERSION||"
+          [[ $RUNTIME_SPEC_VERSION == ?(-)+([0-9]) ]] || \
+            (echo "ERROR: \"${{env.RUNTIME_SPEC_VERSION}}\" is not a valid integer" && exit 10)
+      - name: Set Env Vars
+        run: |
+          echo "WASM_DIR=${{matrix.runtime-dir}}/target/srtool/${{matrix.build-profile}}/wbuild/${{matrix.package}}" >> $GITHUB_ENV
+      # # XXX Keep this step as it lets us skip WASM builds during development/testing
+      # - name: Cache WASM for Testing
+      #   id: cache-wasm
+      #   uses: actions/cache@v3
+      #   with:
+      #     path: ${{env.WASM_DIR}}/${{env.BUILT_WASM_FILENAME}}
+      #     key: ${{runner.os}}-${{matrix.network}}-${{env.NEW_RELEASE_VERSION}}
+      - name: Install srtool-cli
+        run: |
+          cargo install --git https://github.com/chevdor/srtool-cli
+          srtool --version
+      - name: Build Deterministic WASM
+        run: |
+          set -ex
+          srtool build \
+            --default-features="on-chain-release-build,no-metadata-docs,${{matrix.features}}" \
+            --profile=${{matrix.build-profile}} \
+            --package=${{matrix.package}} \
+            --root
 
   verify-js-api-augment:
     needs:
