Chore: Update Rust and JS dependencies (#2476)
# Goal
The goal of this PR is to update Rust and Javascript dependencies

Closes #2419

# Discussion

- Swapped to specific tags for the Polkadot releases as the branch is
constantly being updated
- Moved to Nodejs v22 (as v20 is now just in maintenance mode)

diff --git a/.github/workflows/verify-pr-commit.yml b/.github/workflows/verify-pr-commit.yml
--- a/.github/workflows/verify-pr-commit.yml
+++ b/.github/workflows/verify-pr-commit.yml
@@ -443,7 +443,7 @@ jobs:
       - name: Set up NodeJs
         uses: actions/setup-node@v4
         with:
-          node-version: 20
+          node-version: 22
           cache: "npm"
           cache-dependency-path: js/api-augment/package-lock.json
       - name: Install Latest Versions
@@ -500,7 +500,7 @@ jobs:
       - name: Set up NodeJs
         uses: actions/setup-node@v4
         with:
-          node-version: 20
+          node-version: 22
           cache: "npm"
           cache-dependency-path: js/ethereum-utils/package-lock.json
       - name: Install Latest Versions
@@ -538,7 +538,7 @@ jobs:
       - name: Set up NodeJs
         uses: actions/setup-node@v4
         with:
-          node-version: 20
+          node-version: 22
           cache: "npm"
           cache-dependency-path: js/schemas/package-lock.json
       - name: Install Latest Versions
@@ -856,7 +856,7 @@ jobs:
       - name: Set up NodeJs
         uses: actions/setup-node@v4
         with:
-          node-version: 20
+          node-version: 22
           cache: "npm"
           cache-dependency-path: e2e/package-lock.json
       - name: Install Built api-augment and ethereum-utils
@@ -868,6 +868,11 @@ jobs:
       - name: Lint
         run: npm run lint
         working-directory: e2e
+      - name: E2E Frequency Node Health Check
+        env:
+          Frequency_RPC_PORT: 9944
+        # Simple 20 second 3x health check. If they all fail, then something is up.
+        run: ./scripts/healthcheck.sh || (sleep 10 && ./scripts/healthcheck.sh) || (sleep 10 && ./scripts/healthcheck.sh)
       - name: Run E2E Tests
         working-directory: e2e
         env:
