Paseo Parts (#1900)
# Goal
Trying to get all the release and CI bits cleaned up:

- Release Notes
- Runtimes
- Updated the `spec_name`
- Yaml schema comments
- Misc bits getting testnet vs paseo aligned 🤞

diff --git a/.github/workflows/verify-pr-commit.yml b/.github/workflows/verify-pr-commit.yml
--- a/.github/workflows/verify-pr-commit.yml
+++ b/.github/workflows/verify-pr-commit.yml
@@ -1,3 +1,4 @@
+# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
 name: Verify PR Commit
 concurrency:
   group: ${{github.workflow}}-${{github.ref}}
@@ -96,7 +97,7 @@ jobs:
             git_branch: main
             spec: frequency-local
             branch_alias: main
-          - network: rococo
+          - network: testnet
             spec: frequency-testnet
             branch_alias: pr
           - network: mainnet
@@ -125,7 +126,7 @@ jobs:
             git_branch: main
             spec: frequency-local
             branch_alias: main
-          - network: rococo
+          - network: testnet
             spec: frequency-testnet
             branch_alias: pr
           - network: mainnet
@@ -282,7 +283,7 @@ jobs:
     name: Verify Build Runtime for ${{matrix.network}}
     strategy:
       matrix:
-        network: [rococo, mainnet]
+        network: [testnet, mainnet]
     runs-on: ubuntu-22.04
     steps:
       - run: echo "Just a dummy matrix to satisfy GitHub required checks that were skipped"
@@ -297,7 +298,9 @@ jobs:
     strategy:
       fail-fast: true
       matrix:
-        network: [dev, rococo, mainnet]
+        # Remember, runtimes are separate for each relay chain
+        # We do not release frequency-*-local runtimes however
+        network: [dev, rococo, paseo, mainnet]
         include:
           - network: dev
             build-profile: release
@@ -305,14 +308,21 @@ jobs:
             runtime-dir: runtime/frequency
             built-wasm-file-name-prefix: frequency_runtime
             features: frequency-no-relay
-            wasm-core-version: frequency-rococo
+            wasm-core-version: frequency-testnet
           - network: rococo
             build-profile: release
             package: frequency-runtime
             runtime-dir: runtime/frequency
             built-wasm-file-name-prefix: frequency_runtime
             features: frequency-testnet
-            wasm-core-version: frequency-rococo
+            wasm-core-version: frequency-testnet
+          - network: paseo
+            build-profile: release
+            package: frequency-runtime
+            runtime-dir: runtime/frequency
+            built-wasm-file-name-prefix: frequency_runtime
+            features: frequency-testnet
+            wasm-core-version: frequency-testnet
           - network: mainnet
             build-profile: release
             package: frequency-runtime
@@ -424,7 +434,7 @@ jobs:
         run: |
           chmod 755 ${{env.BIN_FILENAME}}
       - name: Output Metadata
-        run: ${{env.BIN_DIR}}/${{env.BIN_FILENAME}} export-metadata  --chain=frequency-rococo-local --tmp ./js/api-augment/metadata.json
+        run: ${{env.BIN_DIR}}/${{env.BIN_FILENAME}} export-metadata  --chain=frequency-paseo-local --tmp ./js/api-augment/metadata.json
       - name: Build
         run: npm run build
         working-directory: js/api-augment
@@ -596,9 +606,9 @@ jobs:
         working-directory: ${{env.BIN_DIR}}
         run: |
           set -x
-          ./$REF_BIN_FILENAME export-metadata --chain=frequency-rococo-local --tmp metadata-ref.json
+          ./$REF_BIN_FILENAME export-metadata --chain=frequency-paseo-local --tmp metadata-ref.json
           metadata_ref=$(cat metadata-ref.json | jq -r .result)
-          ./$TEST_BIN_FILENAME export-metadata --chain=frequency-rococo-local --tmp metadata.json
+          ./$TEST_BIN_FILENAME export-metadata --chain=frequency-paseo-local --tmp metadata.json
           metadata=$(cat metadata.json | jq -r .result)
           matches=$([ "$metadata" = "$metadata_ref" ] && echo 'true' || echo 'false')
           echo "Metadata matches?: $match"
@@ -722,10 +732,12 @@ jobs:
     container: ghcr.io/libertydsnp/frequency/ci-base-image:latest
     steps:
       - name: Set Env Vars
+        # TODO: UPDATE EXPECTED_GENESIS_STATE_PASEO
         run: |
+          echo "EXPECTED_GENESIS_STATE_PASEO=0x000000000000000000000000000000000000000000000000000000000000000000e3495742b019f5ad49dff7de4040bc965b75eaf46769c24db1027d4ff86fc92703170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400" >> $GITHUB_ENV
           echo "EXPECTED_GENESIS_STATE_ROCOCO=0x000000000000000000000000000000000000000000000000000000000000000000e3495742b019f5ad49dff7de4040bc965b75eaf46769c24db1027d4ff86fc92703170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400" >> $GITHUB_ENV
           echo "EXPECTED_GENESIS_STATE_MAINNET=0x000000000000000000000000000000000000000000000000000000000000000000393a2a0f7778716d006206c5a4787cbf2ea3b26a67379b7a38ee54519d7fd4be03170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400" >> $GITHUB_ENV
-          echo "BIN_FILENAME_ROCOCO=frequency.testnet.frequency-testnet.pr" >> $GITHUB_ENV
+          echo "BIN_FILENAME_TESTNET=frequency.testnet.frequency-testnet.pr" >> $GITHUB_ENV
           echo "BIN_FILENAME_MAINNET=frequency.mainnet.frequency.pr" >> $GITHUB_ENV
       - name: Download Binaries
         id: download-binaries
@@ -741,18 +753,27 @@ jobs:
       - name: Set Binary Permissions
         working-directory: ${{env.BIN_DIR}}
         run: |
-          chmod 755 $BIN_FILENAME_ROCOCO
+          chmod 755 $BIN_FILENAME_TESTNET
           chmod 755 $BIN_FILENAME_MAINNET
-      - name: Test Rococo Genesis State
+      - name: Test Frequency Rococo Genesis State
         working-directory: ${{env.BIN_DIR}}
         run: |
           expected_genesis_state=${{env.EXPECTED_GENESIS_STATE_ROCOCO}}
           echo "Expected genesis state: $expected_genesis_state"
-          actual_genesis_state=$(./${{env.BIN_FILENAME_ROCOCO}} export-genesis-state)
+          actual_genesis_state=$(./${{env.BIN_FILENAME_TESTNET}} --chain=frequency-rococo export-genesis-state)
           echo "Actual genesis state: $actual_genesis_state"
           [ $actual_genesis_state = $expected_genesis_state ] || \
             (echo "ERROR: The actual genesis state does not match the expected" && exit 1)
-      - name: Test Mainnet Genesis State
+      - name: Test Frequency Paseo Genesis State
+        working-directory: ${{env.BIN_DIR}}
+        run: |
+          expected_genesis_state=${{env.EXPECTED_GENESIS_STATE_PASEO}}
+          echo "Expected genesis state: $expected_genesis_state"
+          actual_genesis_state=$(./${{env.BIN_FILENAME_TESTNET}}  --chain=frequency-paseo export-genesis-state)
+          echo "Actual genesis state: $actual_genesis_state"
+          [ $actual_genesis_state = $expected_genesis_state ] || \
+            (echo "ERROR: The actual genesis state does not match the expected" && exit 1)
+      - name: Test Frequency Mainnet Genesis State
         working-directory: ${{env.BIN_DIR}}
         run: |
           expected_genesis_state=${{env.EXPECTED_GENESIS_STATE_MAINNET}}
